{
  "uid" : "1268f7414d802b03",
  "name" : "test_logout",
  "fullName" : "src.tests.automation.test_logout#test_logout",
  "historyId" : "d4f3ade3828f40ffe7afceffe0237ce1",
  "time" : {
    "start" : 1628605402229,
    "stop" : 1628605402229,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "FileNotFoundError: [Errno 2] No such file or directory: 'counter.txt'",
  "statusTrace" : "def test_logout():\n>       file = open('counter.txt', 'r')\nE       FileNotFoundError: [Errno 2] No such file or directory: 'counter.txt'\n\nsrc/tests/automation/test_logout.py:6: FileNotFoundError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "src.tests.automation"
  }, {
    "name" : "suite",
    "value" : "test_logout"
  }, {
    "name" : "host",
    "value" : "fv-az74-184"
  }, {
    "name" : "thread",
    "value" : "3572-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "src.tests.automation.test_logout"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "1268f7414d802b03.json",
  "parameterValues" : [ ]
}